version: "3.8"
services:
   web:
     image: arubiogarcia/pelinx:latest
     ports:
       - "80:80"
     volumes:
       - type: volume
         source: pelis      
         target: /var/www/html/pelis
         volume:
           nocopy: true
     environment:
       USER: toni
       PASSWD: toni              
     deploy:
       replicas: 2     
volumes:
  pelis:         
    driver_opts:  
      type: "nfs"
      o: "addr=192.168.1.134,ro,nolock,soft"
      device: ":/mnt/PelisVistas/Pelis"


