version: "3.8"
services:
  web:
     image: arubiogarcia/pelinx:latest
     ports:
       - "80"
     networks: 
       - proxy 
     volumes:
       - type: volume
         source: pelis      
         target: /var/www/html/pelis
         volume:
           nocopy: true
     environment:
       USER: toni
       PASSWD: toni              
     deploy:
       replicas: 6
       labels:
         traefik.port: 80
         traefik.frontend.rule: "Host:pelinx.192.168.1.134.nip.io,pelinx.192.168.1.132.nip.io"
         traefik.docker.network: 'proxy'

volumes:
  pelis:         
    driver_opts:  
      type: "nfs"
      o: "addr=192.168.1.134,ro,nolock,soft"
      device: ":/mnt/PelisVistas/Pelis"

networks:
  proxy:
    external: true
